# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SlideInTransition' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'Firebase/Firestore'
pod 'DropDown' 
pod 'Firebase/Core'
pod 'Firebase/Crashlytics'
pod 'Firebase/Database'
pod 'Firebase/Storage'
pod 'FSCalendar'

# Pods for Weather
  pod 'Alamofire', '~> 4.7'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'NVActivityIndicatorView'

  # Pods for SlideInTransition

end
